MoovMoney/Areas/Admin/ViewModels/SettingViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using MoovMoney.Models;
using System.ComponentModel.DataAnnotations;

namespace MoovMoney.Areas.Admin.ViewModels
{
    public class SettingViewModel
    {
    }

    public class AgenceViewModel
    {
        public AgenceViewModel()
        {
            Agences = new List<Agence>();
        }

        [Display(Name="Nom de l'agence")]
        [Required(ErrorMessage = "Entrez le nom de l'agence")]
        public string AgenceName { get; set; }
        public List<Agence> Agences { get; set; }
    }

    public class PrefixeViewModel
    {
        [Display(Name = "Préfixes MOOV")]
        [Required]
        public string MoovPrefixestring { get; set; }
        [Display(Name = "Préfixes MOOV")]
        [Required]
        public string MtnPrefixestring { get; set; }
    }
}

MoovMoney/Models/Agence.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MoovMoney.Models
{
    public class Agence
    {
        public int Id { get; set; }
        public string Nom { get; set; }
    }
}

MoovMoney/Areas/Admin/Controllers/SettingsController.cs
using MoovMoney.Controllers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using MoovMoney.Areas.Admin.ViewModels;
using MoovMoney.Models;
using System.Data.Entity.Migrations;
using MoovMoney.Helpers;
using System.Text;

namespace MoovMoney.Areas.Admin.Controllers
{
    [Authorize(Roles = "ADMIN")]
    public class SettingsController : BaseController
    {
        // GET: Admin/Settings
        public async Task<ActionResult> Agences()
        {
            var agences = await DbManager.Agences.OrderBy(a=>a.Nom).ToListAsync();
            return View(new AgenceViewModel(){Agences=agences});
        }

        [HttpPost]
        public async Task<ActionResult> Agences(AgenceViewModel vm)
        {
            if(ModelState.IsValid)
            {
                var agence = new Agence() { Nom = vm.AgenceName };
                DbManager.Agences.AddOrUpdate(a => a.Nom, agence);
                await DbManager.SaveChangesAsync();
            }
            
            return RedirectToAction("Agences");
        }

        public async Task<ActionResult> Prefixes()
        {
            var moovprefixes = DbManager.Networks.FirstOrDefault(n => n.Name == Common.NetworkName.MOOV).Prefixes.ToList();
            var mtnprefixes = DbManager.Networks.FirstOrDefault(n => n.Name == Common.NetworkName.MTN).Prefixes.ToList();
            var vm = new PrefixeViewModel { MoovPrefixestring = GetStringPrefixes(moovprefixes),MtnPrefixestring=GetStringPrefixes(mtnprefixes) };
            return View(vm);
        }

        [HttpPost]
        public async Task<ActionResult> Prefixes(PrefixeViewModel vm)
        {
            if(ModelState.IsValid)
            {
                var moovprefixes = GetPrefixesFrom(vm.MoovPrefixestring);
                var mtnprefixes = GetPrefixesFrom(vm.MtnPrefixestring);
                DbManager.Networks.FirstOrDefault(n => n.Name == Common.NetworkName.MOOV).Prefixes.Clear();
                DbManager.Networks.FirstOrDefault(n => n.Name == Common.NetworkName.MTN).Prefixes.Clear();

                DbManager.Networks.FirstOrDefault(n => n.Name == Common.NetworkName.MOOV).Prefixes = moovprefixes;
                DbManager.Networks.FirstOrDefault(n => n.Name == Common.NetworkName.MTN).Prefixes = mtnprefixes;
                await DbManager.SaveChangesAsync();
            }
            
            return RedirectToAction("Prefixes");
        }

        public async Task<ActionResult> DeleteAgence(int id)
        {
            var agenceToDelete = DbManager.Agences.FirstOrDefault(a => a.Id == id);
            DbManager.Agences.Remove(agenceToDelete);
            await DbManager.SaveChangesAsync();
            return RedirectToAction("Agences");
        }

        private List<NetworkPrefix> GetPrefixesFrom(string prefString)
        {
            string[] prefs = prefString.Split(',');
            List<NetworkPrefix> preflist = new List<NetworkPrefix>();
            foreach (var ps in prefs)
                preflist.Add(new NetworkPrefix() { Prefix = ps });
            return preflist;
        }

        private string GetStringPrefixes(List<NetworkPrefix> prefixes)
        {
            StringBuilder str = new StringBuilder();
            foreach (var pref in prefixes.Select(p=>p.Prefix))
                str.Append(pref + " ,");
            return str.ToString();
        }
    }
}

MoovMoney/Areas/Admin/Views/Settings/Agences.cshtml
@using MoovMoney.Models
@model MoovMoney.Areas.Admin.ViewModels.AgenceViewModel

@{
    ViewBag.Title = "Agences";
    int count = 0;
}

<div class="row">

    <div class="col-lg-6 col-md-6 col-sm-12">

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Agence</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    <div class="col-md-10">
                        @Html.LabelFor(model => model.AgenceName, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.AgenceName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.AgenceName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div >
                        <input type="submit" value="Ajouter" class="btn btn-primary" />
                    </div>
                </div>
            </div>
        }
        </div>
    </div>

<br />  <br />  

        <div class="row">

            <div class="col-lg-6 col-md-6 col-sm-12">
                <div class="panel">
                    <header class="panel-heading">
                        <h4>@ViewBag.title</h4>

                        <hr />
                    </header>

                    <div class="panel-body">
                        <div class="card">
                            @if (Model != null && Model.Agences.Count() > 0)
                            {
                                <table id="table" class="table " cellspacing="0" width="100%">
                                    <thead class="thead-default rgba-red-light">
                                        <tr>
                                            <th><b>#</b></th>
                                            <th><b>NOM</b></th>
                                            <th><b>ACTIONS</b></th>
                                        </tr>
                                    </thead>

                                    <tbody>
                                        @foreach (var ag in Model.Agences)
                                        {
                                            count++;
                                            <tr>
                                                <td>@count</td>
                                                <td>@ag.Nom</td>
                                                <td>
                                                    <a onclick="javascript: location.href = '@Url.Action("DeleteAgence", "Settings", new { area = "Admin", id = @ag.Id })'"  class="btn btn-default btn-xs"><i class="fa fa-trash"></i> </a>
                                                </td>
                                                
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            }
                            else
                            {
                                <h4 class="text-center" style="padding:10px">Aucune agence</h4>
                            }

                        </div>
                    </div>


                </div>

            </div>
        </div>



        @section scripts {
            @Scripts.Render("~/bundles/jqueryval")
        }

MoovMoney/Areas/Admin/Views/Settings/Prefixes.cshtml
@model MoovMoney.Areas.Admin.ViewModels.PrefixeViewModel

@{
    ViewBag.Title = "Prefixes";
}

@section styles {
<link href="~/Areas/Admin/Content/gentella/vendors/jquery.tagsinput/src/jquery.tagsinput.css" rel="stylesheet" />
    
}
@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Liste des préfixes</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Préfixes MOOV", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10 control-group">               
                <div class="col-md-9 col-sm-9 col-xs-12">
                    <input id="tags_3" type="text" class="tags form-control" name="MoovPrefixestring" value="@Model.MoovPrefixestring" />
                    <div id="suggestions-container" style="position: relative; float: left; width: 250px; margin: 10px;"></div>
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Préfixes MTN", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10 control-group">
                <div class="col-md-9 col-sm-9 col-xs-12">
                    <input id="tags_2" type="text"  class="tags form-control" name="MtnPrefixestring" value="@Model.MtnPrefixestring" />
                    <div id="suggestions-container" style="position: relative; float: left; width: 250px; margin: 10px;"></div>
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Valider" class="btn btn-default" />
            </div>
        </div>
    </div>
}



@section scripts {
    
<script src="~/Areas/Admin/Content/gentella/vendors/jquery.tagsinput/src/jquery.tagsinput.js"></script>
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        $(document).load(new function () {
            $('#tags_2').tagsInput({
                width: 'auto',
                defaultText:"Préfixe"
            });
            $('#tags_3').tagsInput({
                width: 'auto',
                defaultText: "Préfixe"
            });
        })
        
    </script>
}