MoovMoney/Controllers/TransactionListController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MoovMoney.Models;
using MoovMoney.ViewModels;
using OfficeOpenXml;
using System.IO;
using Syroot.Windows.IO;
using log4net;

namespace MoovMoney.Controllers
{
    public class TransactionListController : BaseController
    {
        public static readonly ILog logger = LogManager.GetLogger("UserTransactions");
        // GET: TransactionList
        public async Task<ActionResult> Index(string filter)
        {
            try
            {
                var trans = await GetUserTransactions();
                switch (filter)
                {
                    case "WEEK":
                        DateTime startDate = DateTime.Today.Date.AddDays(-(int)DateTime.Today.DayOfWeek), // prev sunday 00:00
                                 endDate = startDate.AddDays(7);
                        trans = trans.Where(t => (t.timestamp.Date >= startDate && t.timestamp.Date < endDate)).ToList();
                        ViewBag.FilterTitle = "Cette semaine";
                        break;
                    case "MONTH":
                        trans = trans.Where(t => (t.timestamp.Date.Month == DateTime.Today.Month && t.timestamp.Date.Year == DateTime.Today.Year)).ToList();
                        ViewBag.FilterTitle = "Ce mois";
                        break;
                    default:
                        trans = trans.Where(t => t.timestamp.Date == DateTime.Now.Date).ToList();
                        ViewBag.FilterTitle = "Aujourd'hui";
                        break;
                }
                var vm = new TransactionListVM { Transactions = trans };
                return View(vm);
            }
            catch (Exception ex)
            {
                logger.Error(CurrentUser.UserName, ex);
                throw;
            }
            
        }

        [HttpPost]
        public async Task<ActionResult> Index(TransactionListVM vm)
        {
            try
            {
                var trans = await GetUserTransactions();
                if (!string.IsNullOrWhiteSpace(vm.PhoneNumber))
                    trans = trans.Where(t => t.msisdn.Contains(vm.PhoneNumber.Trim())).ToList();
                vm.Transactions = trans;
                return View(vm);
            }
            catch (Exception ex)
            {
                logger.Error(CurrentUser.UserName, ex);
                throw;
            }
            
        }

        public ActionResult ExportToExcel()
        {
            try
            {
                var DirPath = KnownFolders.PublicDownloads.Path;
                String fileName = Path.Combine(DirPath, "transactions.xlsx");
                var trans = DbManager.Transactions.ToList();
                using (ExcelPackage pck = new ExcelPackage())
                {
                    ExcelWorksheet worksheet = pck.Workbook.Worksheets.Add("Transactions");
                    worksheet.Row(1).Height = 20;
                    worksheet.Row(1).Style.Font.Bold = true;
                    worksheet.Cells[1, 1].Value = "N°";
                    worksheet.Cells[1, 2].Value = "NOM";
                    worksheet.Cells[1, 3].Value = "PRENOMS";
                    worksheet.Cells[1, 4].Value = "NUMERO";
                    worksheet.Cells[1, 5].Value = "MONTANT";
                    worksheet.Cells[1, 6].Value = "DATE";
                    for (int i = 0; i < trans.Count; i++)
                    {
                        Transaction t = trans[i];
                        worksheet.Cells[i + 2, 1].Value = i + 1;
                        worksheet.Cells[i + 2, 2].Value = t.lastname;
                        worksheet.Cells[i + 2, 3].Value = t.firstname;
                        worksheet.Cells[i + 2, 4].Value = t.msisdn;
                        worksheet.Cells[i + 2, 5].Value = t.transamount;
                        worksheet.Cells[i + 2, 6].Value = t.timestamp.ToLongDateString();

                        worksheet.Column(i + 1).AutoFit();
                    }

                    //Create excel file on physical disk    
                    FileInfo info = new FileInfo(fileName);
                    pck.SaveAs(info);
                }
                return File(fileName, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Transactions.xlsx");
            }
            catch (Exception ex)
            {
                logger.Error(CurrentUser.UserName, ex);
                throw;
            }
            
        }

        private async Task<List<Transaction>> GetUserTransactions()
        {
            var id = CurrentUser.Id;
            return await DbManager.Transactions.Where(t => t.User.Id == id)
                                    .OrderByDescending(t => t.timestamp).ToListAsync();
        }

        
        
       
    }
}

MoovMoney/Views/TransactionList/Index.cshtml
@using MoovMoney.Models
@using MoovMoney.ViewModels
@model TransactionListVM

@{
    ViewBag.Title = "Index";
}

@section styles{
    
<link href="~/Content/dataTables.bootstrap.min.css" rel="stylesheet" />
}


<h4>Liste des transactions</h4>

<hr class="mt-2 mb-2">
@using (Html.BeginForm())
{
    <div class="row">
        <div class="col-md-4 col-lg-4">
            <div class="btn-group">
                <button class="btn btn-outline-danger dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">@ViewBag.FilterTitle</button>

                <div class="dropdown-menu">
                    <a class="dropdown-item" href="@Url.Action("Index", "TransactionList")">Aujourd'hui</a>
                    <a class="dropdown-item" href="@Url.Action("Index", "TransactionList", new {filter=TransactionFilters.THIS_WEEK })">Cette semaine</a>
                    <a class="dropdown-item" href="@Url.Action("Index", "TransactionList", new {filter=TransactionFilters.THIS_MONTH })">Ce mois</a>
                </div>
            </div>
        </div>
        <div class="col-md-4 col-lg-4">
            <div class="md-form input-group">
                <input name="PhoneNumber" value="@Model.PhoneNumber" style="margin-top:4px" type="search" class="form-control input-alternate" placeholder="Rechercher un numero">
                <span class="input-group-btn">
                    <button  value="phone" class="btn btn-outline-danger btn-sm" type="submit">Go!</button>
                </span>
            </div>
        </div>
        <div class="col-md-4 col-lg-4 text-right">
            <a id="btn" href="@Url.Action("ExportToExcel")" class="btn btn-danger btn-red-uba">Exporter en Excel</a>
        </div>

    </div>
}

<div class="card">
    @if (Model.Transactions != null && Model.Transactions.Count() > 0)
    {
        <table id="example" class="table " cellspacing="0" width="100%">
            <thead class="thead-default rgba-red-light">
                <tr>
                    <th><b>NOM ET PRENOMS</b></th>
                    <th><b>N° TELEPHONE</b></th>
                    <th><b>MONTANT</b></th>
                    <th><b>DATE DU TRANSFERT</b></th>
                </tr>
            </thead>

            <tbody>
                  @foreach (var t in Model.Transactions)
                  {
                        <tr>
                            <td>@t.lastname @t.firstname</td>
                            <td>@t.msisdn</td>
                            <td>@t.transamount F CFA</td>
                            <td>@t.timestamp.ToShortDateString() à @t.timestamp.ToShortTimeString()</td>
                        </tr>
                  }              
            </tbody>
        </table>
    }
    else
    {
        <h4 class="text-center" style="padding:10px">Aucune transaction trouvée</h4>
    }
    
</div>
@section scripts{
    @Scripts.Render("~/bundles/jqueryval")    
    <script src="~/Scripts/jquery.dataTables.min.js"></script>
    <script src="~/Scripts/dataTables.bootstrap.min.js"></script>


    <script>
        $(document).ready(function () {
            $('#examplee').DataTable();
        });
    </script>

}